import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import { useTourData } from '../hooks/useTourData';
import NavBar from '../components/NavBar';
import { Button } from '@/components/ui/button';
import MapSearchModal from '../components/MapSearchModal';
import ProcessingPhase from '../components/ProcessingPhase';
import TourEditInput from '../components/TourEditInput';
import TourEditReview from '../components/TourEditReview';
import { MapPinned, CloudOff, RefreshCw } from 'lucide-react';

const DEFAULT_LAYERS = [
  { id: 'novel', name: '小说场景', icon: '📖', color: '#c0392b' },
  { id: 'history', name: '历史掌故', icon: '🏛', color: '#d35400' },
  { id: 'folklore', name: '民间传说', icon: '🐉', color: '#27ae60' },
  { id: 'customs', name: '民俗风情', icon: '🎭', color: '#2980b9' },
];

export default function TourEdit() {
  const { tourId } = useParams();
  const { tour, loading, source: dataSource, reload: reloadTour } = useTourData(tourId);
  const { user } = useAuth();
  const navigate = useNavigate();

  const isNew = !tourId;
  const isOwner = tour && user && tour.userId === user.id;

  // ── Phase tracking ──
  // 'input' = user fills info → 'processing' = waiting for AI → 'review' = AI done, user reviews
  const [phase, setPhase] = useState('input');

  // ── Basic Info ──
  const [title, setTitle] = useState('');
  const [subtitle, setSubtitle] = useState('');
  const [primaryColor, setPrimaryColor] = useState('#c0392b');
  const [destName, setDestName] = useState('');
  const [destRegion, setDestRegion] = useState('');
  const [isPublic, setIsPublic] = useState(false);

  // Source material
  const [novelTitle, setNovelTitle] = useState('');
  const [novelAuthor, setNovelAuthor] = useState('');
  const [novelEra, setNovelEra] = useState('');
  const [novelSynopsis, setNovelSynopsis] = useState('');
  const [sourceText, setSourceText] = useState('');

  // ── Locations & Content (generated by AI) ──
  const [locations, setLocations] = useState([]);
  const [contentLayers, setContentLayers] = useState(DEFAULT_LAYERS);
  const [editingLoc, setEditingLoc] = useState(null);
  const [editingLayer, setEditingLayer] = useState('novel');

  // ── Routes (generated by AI) ──
  const [routes, setRoutes] = useState([]);

  // ── Map search modal ──
  const [showMapSearch, setShowMapSearch] = useState(false);

  // ── UI state ──
  const [saving, setSaving] = useState(false);
  const [saveMsg, setSaveMsg] = useState('');
  const [saveMsgType, setSaveMsgType] = useState('ok'); // ok | info | err — 驱动横幅配色，替代 emoji 判断
  const flash = (msg, type = 'err') => { setSaveMsg(msg); setSaveMsgType(type); };
  const [draftTourId, setDraftTourId] = useState(tourId);
  const [processingError, setProcessingError] = useState('');
  // 'ai' = retry reruns AI processing; 'reload' = AI done, just refetch results
  const [retryMode, setRetryMode] = useState('ai');
  // Token to invalidate a stale AI run (user went back / skipped / retried)
  const aiRunRef = useRef(0);
  // 重新处理计数：递增以强制重挂载 ProcessingPhase，重置轮询
  const [retryCount, setRetryCount] = useState(0);

  // Refetch results after AI completes — retry up to 5 times with
  // increasing delays, because the long POST can exhaust Chrome's
  // connection pool and cause transient ERR_INTERNET_DISCONNECTED.
  const loadResults = async (runId) => {
    for (let i = 0; i < 5; i++) {
      if (aiRunRef.current !== runId) return true;
      const fresh = await reloadTour();
      if (aiRunRef.current !== runId) return true;
      if (fresh && fresh.locations && fresh.locations.length > 0) {
        setProcessingError('');
        setPhase('review');
        return true;
      }
      // Wait before retry: 2s, 4s, 8s, 16s
      if (i < 4) await new Promise(r => setTimeout(r, (2 ** (i + 1)) * 1000));
    }
    setRetryMode('reload');
    setProcessingError('AI 处理已完成，但网络异常导致结果加载失败。点「重试」重新加载（不会重复调用 AI）。');
    return false;
  };

  // Populate from loaded tour
  useEffect(() => {
    if (!tour) return;
    setTitle(tour.meta?.title || '');
    setSubtitle(tour.meta?.subtitle || '');
    setPrimaryColor(tour.theme?.primaryColor || '#c0392b');
    setDestName(tour.destination?.name || '');
    setDestRegion(tour.destination?.region || '');
    setIsPublic(tour.isPublic || false);
    setNovelTitle(tour.source?.title || '');
    setNovelAuthor(tour.source?.author || '');
    setNovelEra(tour.source?.era || '');
    setNovelSynopsis(tour.source?.synopsis || '');
    setLocations(tour.locations || []);
    setRoutes(tour.routes || []);
    setContentLayers(tour.contentLayers?.length ? tour.contentLayers : DEFAULT_LAYERS);

    // If locations already exist, we're in review phase
    if (tour.locations && tour.locations.length > 0) {
      setPhase('review');
    }
  }, [tour]);

  // ── Save draft and request AI processing ──
  const handleSaveDraft = async () => {
    if (!user) { flash('请先登录'); return; }
    if (!title.trim()) { flash('请输入标题'); return; }
    setSaving(true);
    setSaveMsg('');

    const tourData = {
      title: title.trim(),
      subtitle: subtitle.trim(),
      theme: { primaryColor },
      source: {
        type: 'novel',
        title: novelTitle,
        author: novelAuthor,
        era: novelEra,
        synopsis: novelSynopsis,
        rawText: sourceText,
      },
      destination: { name: destName, region: destRegion, type: 'mountain' },
      is_public: false,
      status: 'processing',
    };

    try {
      let uuid = draftTourId;
      if (!uuid) {
        const { data, error } = await supabase
          .from('tours')
          .insert({ ...tourData, user_id: user.id })
          .select('id');
        if (error) { console.error('Insert fail:', error); throw error; }
        if (!data || data.length === 0) throw new Error('保存失败');
        uuid = data[0].id;
        setDraftTourId(uuid);
        navigate(`/tour/${uuid}/edit`, { replace: true });
      } else {
        await supabase.from('tours').update(tourData).eq('id', uuid);
      }

      setPhase('processing');
      flash(`草稿已保存 (ID: ${uuid})`, 'ok');
    } catch (e) {
      flash(e.message);
    } finally {
      setSaving(false);
    }
  };

  // ── 保存基本信息（已有导览）：只更新标题/目的地等，不触发 AI 重新处理 ──
  const handleSaveBasic = async () => {
    if (!user) { flash('请先登录'); return; }
    if (!title.trim()) { flash('请输入标题'); return; }
    if (!draftTourId) { flash('尚未保存草稿'); return; }
    setSaving(true);
    setSaveMsg('');
    const tourData = {
      title: title.trim(),
      subtitle: subtitle.trim(),
      theme: { primaryColor },
      source: {
        type: 'novel',
        title: novelTitle,
        author: novelAuthor,
        era: novelEra,
        synopsis: novelSynopsis,
        rawText: sourceText,
      },
      destination: { name: destName, region: destRegion, type: 'mountain' },
      is_public: isPublic,
    };
    try {
      await supabase.from('tours').update(tourData).eq('id', draftTourId);
      await reloadTour();
      flash('基本信息已保存', 'ok');
      setPhase('review');
    } catch (e) {
      flash(e.message);
    } finally {
      setSaving(false);
    }
  };

  // ── Re-process: 重置 status=processing，触发 UPDATE 触发器重新调用 Edge Function ──
  const handleReprocess = async () => {
    if (!user) { flash('请先登录'); return; }
    if (!draftTourId) { flash('尚未保存草稿'); return; }
    setProcessingError('');
    try {
      await supabase.from('tours').update({ status: 'processing' }).eq('id', draftTourId);
      setRetryCount(c => c + 1); // 强制重挂载 ProcessingPhase，重置轮询
      setPhase('processing');
    } catch (e) {
      flash(e.message);
    }
  };

  // ── Location helpers ──
  const addLocation = (loc) => {
    setLocations(prev => [...prev, loc]);
    setEditingLoc(loc);
    setShowMapSearch(false);
  };

  const removeLocation = (id) => {
    setLocations(prev => prev.filter(l => l.id !== id));
    if (editingLoc?.id === id) setEditingLoc(null);
    setRoutes(prev => prev.map(r => ({ ...r, stops: r.stops.filter(s => s !== id) })));
  };

  const updateLocation = (id, updates) => {
    setLocations(prev => prev.map(l => l.id === id ? { ...l, ...updates } : l));
    setEditingLoc(prev => prev?.id === id ? { ...prev, ...updates } : prev);
  };

  const updateLayerContent = (locId, layerKey, content) => {
    setLocations(prev => prev.map(l => {
      if (l.id !== locId) return l;
      return { ...l, layers: { ...l.layers, [layerKey]: content } };
    }));
  };

  // ── Route helpers ──
  const addRoute = () => {
    setRoutes(prev => [...prev, {
      id: `route_${Date.now()}`,
      day: `第${prev.length + 1}天`,
      title: '',
      stops: [],
      narrative: '',
    }]);
  };

  const updateRoute = (id, updates) => {
    setRoutes(prev => prev.map(r => r.id === id ? { ...r, ...updates } : r));
  };

  const removeRoute = (id) => {
    setRoutes(prev => prev.filter(r => r.id !== id));
  };

  const toggleRouteStop = (routeId, locId) => {
    setRoutes(prev => prev.map(r => {
      if (r.id !== routeId) return r;
      const exists = r.stops.includes(locId);
      return { ...r, stops: exists ? r.stops.filter(s => s !== locId) : [...r.stops, locId] };
    }));
  };

  // ── Save all (final) ──
  const handleSaveAll = async () => {
    if (!user) { flash('请先登录'); return; }
    setSaving(true);
    setSaveMsg('');

    const tourData = {
      title: title.trim(), subtitle: subtitle.trim(),
      theme: { primaryColor },
      source: { type: 'novel', title: novelTitle, author: novelAuthor, era: novelEra, synopsis: novelSynopsis },
      destination: { name: destName, region: destRegion, type: 'mountain' },
      is_public: isPublic,
    };

    try {
      const uuid = draftTourId;
      await supabase.from('tours').update(tourData).eq('id', uuid);

      await supabase.from('content_layers').delete().eq('tour_id', uuid);
      if (contentLayers.length > 0) {
        await supabase.from('content_layers').insert(
          contentLayers.map((l, i) => ({
            tour_id: uuid, layer_key: l.id, name: l.name, icon: l.icon, color: l.color, sort_order: i,
          }))
        );
      }

      await supabase.from('locations').delete().eq('tour_id', uuid);
      if (locations.length > 0) {
        await supabase.from('locations').insert(
          locations.map((loc, i) => ({
            id: loc.id, tour_id: uuid, name: loc.name,
            lat: loc.lat, lng: loc.lng, elevation: loc.elevation || '',
            importance: loc.importance || 3, tags: loc.tags || [],
            layers: loc.layers || {}, reflection: loc.reflection || '',
            practical: loc.practical || {}, sort_order: i,
          }))
        );
      }

      await supabase.from('routes').delete().eq('tour_id', uuid);
      if (routes.length > 0) {
        await supabase.from('routes').insert(
          routes.map((r, i) => ({
            id: r.id, tour_id: uuid, day_label: r.day,
            title: r.title, stops: r.stops, narrative: r.narrative || '', sort_order: i,
          }))
        );
      }

      flash('保存成功！', 'ok');
    } catch (e) {
      flash(e.message);
    } finally {
      setSaving(false);
    }
  };

  // ── Render ──
  if (loading) return <div className="min-h-screen bg-background flex items-center justify-center text-muted-foreground">加载中...</div>;
  if (!isNew && !isOwner && tour) {
    return (
      <div className="min-h-screen bg-background">
        <NavBar title="无权限" />
        <div className="flex items-center justify-center text-center p-4 pt-20">
          <div>
            <p className="text-muted-foreground mb-4">你没有编辑此导览的权限</p>
            <Button onClick={() => navigate(`/tour/${tourId}`)}>返回导览</Button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Header */}
      <NavBar
        title={isNew ? '创建新导览' : phase === 'input' ? '编辑基本信息' : '编辑导览'}
        rightContent={
          phase === 'review' ? (
            <Button size="sm" onClick={handleSaveAll} disabled={saving}>
              {saving ? '保存中...' : '保存'}
            </Button>
          ) : false
        }
      />

      {saveMsg && (
        <div className={`px-4 py-2.5 text-xs text-center font-medium flex items-center justify-center gap-3 ${
          saveMsgType === 'ok' ? 'bg-pine/10 text-pine' :
          saveMsgType === 'info' ? 'bg-dai/10 text-dai' :
          'bg-primary/10 text-primary'
        }`}>{saveMsg}{saveMsgType === 'ok' && <a href={`/tour/${draftTourId}`} className="underline hover:text-primary transition-colors">查看导览 →</a>}</div>
      )}

      <div className="flex-1 overflow-y-auto p-4 max-w-2xl mx-auto w-full pb-24">

        {/* ════════════════════════════════════════════════ */}
        {/* PHASE 1: Input — User fills basic info + source */}
        {/* ════════════════════════════════════════════════ */}
        {phase === 'input' && (
          <TourEditInput
            title={title} setTitle={setTitle} subtitle={subtitle} setSubtitle={setSubtitle}
            primaryColor={primaryColor} setPrimaryColor={setPrimaryColor}
            destName={destName} setDestName={setDestName} destRegion={destRegion} setDestRegion={setDestRegion}
            isPublic={isPublic} setIsPublic={setIsPublic}
            novelTitle={novelTitle} setNovelTitle={setNovelTitle} novelAuthor={novelAuthor} setNovelAuthor={setNovelAuthor}
            novelEra={novelEra} setNovelEra={setNovelEra} novelSynopsis={novelSynopsis} setNovelSynopsis={setNovelSynopsis}
            sourceText={sourceText} setSourceText={setSourceText}
            draftTourId={draftTourId} saving={saving}
            handleSaveBasic={handleSaveBasic} handleSaveDraft={handleSaveDraft}
          />
        )}

        {/* ════════════════════════════════════════════════ */}
        {/* PHASE 2: Processing — waiting for AI */}
        {/* ════════════════════════════════════════════════ */}
        {phase === 'processing' && (
          <ProcessingPhase
            key={retryCount}
            draftTourId={draftTourId}
            title={title}
            destName={destName}
            destRegion={destRegion}
            novelTitle={novelTitle}
            novelAuthor={novelAuthor}
            sourceText={sourceText}
            onCheckDone={async () => {
              // Load tour data BEFORE entering review, so user never sees blank error page
              for (let i = 0; i < 5; i++) {
                const fresh = await reloadTour();
                if (fresh && fresh.locations && fresh.locations.length > 0) {
                  setPhase('review');
                  return;
                }
                if (i < 4) await new Promise(r => setTimeout(r, (i + 1) * 2000));
              }
              setPhase('review'); // fallback: show error+retry UI
            }}
            onSkip={() => setPhase('review')}
            onBack={() => setPhase('input')}
            onRetry={handleReprocess}
          />
        )}

        {/* ════════════════════════════════════════════════ */}
        {/* PHASE 3: Review — locations, content, routes */}
        {/* ════════════════════════════════════════════════ */}
        {phase === 'review' && loading && (
          <div className="text-center py-16 text-muted-foreground">加载数据中...</div>
        )}
        {phase === 'review' && !loading && (!tour || (!locations.length && !routes.length)) && (
          tour ? (
            // 导览加载成功，但 AI 没有生成任何地点 —— 重试加载没用，给出正确操作
            <div className="text-center py-16 space-y-4">
              <div className="w-14 h-14 mx-auto rounded-full border border-border bg-card flex items-center justify-center">
                <MapPinned className="h-6 w-6 text-muted-foreground" />
              </div>
              <p className="text-muted-foreground">AI 没有生成任何地点</p>
              <p className="text-muted-foreground text-xs">可能原因：源文本过少、地点未识别、或坐标校验全被过滤</p>
              <div className="flex gap-2 justify-center">
                <button onClick={() => setPhase('input')}
                  className="px-6 py-2 bg-black/[0.05] text-muted-foreground rounded-lg text-sm">← 修改基本信息</button>
                <button onClick={handleReprocess}
                  className="px-6 py-2 bg-primary text-primary-foreground rounded-lg text-sm flex items-center gap-1.5">
                  <RefreshCw className="h-3.5 w-3.5" /> AI 重新分析
                </button>
              </div>
            </div>
          ) : (
            // 导览数据加载失败（网络/权限问题）
            <div className="text-center py-16 space-y-4">
              <div className="w-14 h-14 mx-auto rounded-full border border-border bg-card flex items-center justify-center">
                <CloudOff className="h-6 w-6 text-muted-foreground" />
              </div>
              <p className="text-muted-foreground">数据加载失败，请检查网络后重试</p>
              <button onClick={() => reloadTour()} className="px-6 py-2 bg-primary text-primary-foreground rounded-lg text-sm flex items-center gap-1.5 mx-auto">
                <RefreshCw className="h-3.5 w-3.5" /> 重试加载
              </button>
            </div>
          )
        )}
        {phase === 'review' && !loading && tour && (locations.length > 0 || routes.length > 0) && (
          <TourEditReview
            locations={locations} routes={routes} contentLayers={contentLayers}
            editingLoc={editingLoc} editingLayer={editingLayer} isPublic={isPublic}
            onSetPhase={setPhase} setIsPublic={setIsPublic}
            onShowMapSearch={() => setShowMapSearch(true)}
            onSetEditingLoc={setEditingLoc} onSetEditingLayer={setEditingLayer}
            updateLocation={updateLocation} removeLocation={removeLocation} updateLayerContent={updateLayerContent}
            addRoute={addRoute} updateRoute={updateRoute} removeRoute={removeRoute} toggleRouteStop={toggleRouteStop}
            onReprocess={handleReprocess}
          />
        )}
      </div>

      <MapSearchModal
        show={showMapSearch}
        onClose={() => setShowMapSearch(false)}
        onAdd={addLocation}
        initialRegion={destRegion}
      />
    </div>
  );
}
