import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import { useTourData } from '../hooks/useTourData';
import NavBar from '../components/NavBar';
import { Button } from '@/components/ui/button';
import MapSearchModal from '../components/MapSearchModal';
import ProcessingPhase from '../components/ProcessingPhase';

const DEFAULT_LAYERS = [
  { id: 'novel', name: '小说场景', icon: '📖', color: '#c0392b' },
  { id: 'history', name: '历史掌故', icon: '🏛', color: '#d35400' },
  { id: 'folklore', name: '民间传说', icon: '🐉', color: '#27ae60' },
  { id: 'customs', name: '民俗风情', icon: '🎭', color: '#2980b9' },
];

export default function TourEdit() {
  const { tourId } = useParams();
  const { tour, loading, source: dataSource, reload: reloadTour } = useTourData(tourId);
  const { user } = useAuth();
  const navigate = useNavigate();

  const isNew = !tourId;
  const isOwner = tour && user && tour.userId === user.id;

  // ── Phase tracking ──
  // 'input' = user fills info → 'processing' = waiting for AI → 'review' = AI done, user reviews
  const [phase, setPhase] = useState('input');

  // ── Basic Info ──
  const [title, setTitle] = useState('');
  const [subtitle, setSubtitle] = useState('');
  const [primaryColor, setPrimaryColor] = useState('#c0392b');
  const [destName, setDestName] = useState('');
  const [destRegion, setDestRegion] = useState('');
  const [isPublic, setIsPublic] = useState(false);

  // Source material
  const [novelTitle, setNovelTitle] = useState('');
  const [novelAuthor, setNovelAuthor] = useState('');
  const [novelEra, setNovelEra] = useState('');
  const [novelSynopsis, setNovelSynopsis] = useState('');
  const [sourceText, setSourceText] = useState('');

  // ── Locations & Content (generated by AI) ──
  const [locations, setLocations] = useState([]);
  const [contentLayers, setContentLayers] = useState(DEFAULT_LAYERS);
  const [editingLoc, setEditingLoc] = useState(null);
  const [editingLayer, setEditingLayer] = useState('novel');

  // ── Routes (generated by AI) ──
  const [routes, setRoutes] = useState([]);

  // ── Map search modal ──
  const [showMapSearch, setShowMapSearch] = useState(false);

  // ── UI state ──
  const [saving, setSaving] = useState(false);
  const [saveMsg, setSaveMsg] = useState('');
  const [draftTourId, setDraftTourId] = useState(tourId);
  const [processingError, setProcessingError] = useState('');
  // 'ai' = retry reruns AI processing; 'reload' = AI done, just refetch results
  const [retryMode, setRetryMode] = useState('ai');
  // Token to invalidate a stale AI run (user went back / skipped / retried)
  const aiRunRef = useRef(0);
  // 重新处理计数：递增以强制重挂载 ProcessingPhase，重置轮询
  const [retryCount, setRetryCount] = useState(0);

  // Refetch results after AI completes — retry up to 5 times with
  // increasing delays, because the long POST can exhaust Chrome's
  // connection pool and cause transient ERR_INTERNET_DISCONNECTED.
  const loadResults = async (runId) => {
    for (let i = 0; i < 5; i++) {
      if (aiRunRef.current !== runId) return true;
      const fresh = await reloadTour();
      if (aiRunRef.current !== runId) return true;
      if (fresh && fresh.locations && fresh.locations.length > 0) {
        setProcessingError('');
        setPhase('review');
        return true;
      }
      // Wait before retry: 2s, 4s, 8s, 16s
      if (i < 4) await new Promise(r => setTimeout(r, (2 ** (i + 1)) * 1000));
    }
    setRetryMode('reload');
    setProcessingError('AI 处理已完成，但网络异常导致结果加载失败。点「重试」重新加载（不会重复调用 AI）。');
    return false;
  };

  // Populate from loaded tour
  useEffect(() => {
    if (!tour) return;
    setTitle(tour.meta?.title || '');
    setSubtitle(tour.meta?.subtitle || '');
    setPrimaryColor(tour.theme?.primaryColor || '#c0392b');
    setDestName(tour.destination?.name || '');
    setDestRegion(tour.destination?.region || '');
    setIsPublic(tour.isPublic || false);
    setNovelTitle(tour.source?.title || '');
    setNovelAuthor(tour.source?.author || '');
    setNovelEra(tour.source?.era || '');
    setNovelSynopsis(tour.source?.synopsis || '');
    setLocations(tour.locations || []);
    setRoutes(tour.routes || []);
    setContentLayers(tour.contentLayers?.length ? tour.contentLayers : DEFAULT_LAYERS);

    // If locations already exist, we're in review phase
    if (tour.locations && tour.locations.length > 0) {
      setPhase('review');
    }
  }, [tour]);

  // ── Save draft and request AI processing ──
  const handleSaveDraft = async () => {
    if (!user) { setSaveMsg('请先登录'); return; }
    if (!title.trim()) { setSaveMsg('请输入标题'); return; }
    setSaving(true);
    setSaveMsg('');

    const tourData = {
      title: title.trim(),
      subtitle: subtitle.trim(),
      theme: { primaryColor },
      source: {
        type: 'novel',
        title: novelTitle,
        author: novelAuthor,
        era: novelEra,
        synopsis: novelSynopsis,
        rawText: sourceText,
      },
      destination: { name: destName, region: destRegion, type: 'mountain' },
      is_public: false,
      status: 'processing',
    };

    try {
      let uuid = draftTourId;
      if (!uuid) {
        const { data, error } = await supabase
          .from('tours')
          .insert({ ...tourData, user_id: user.id })
          .select('id');
        if (error) { console.error('Insert fail:', error); throw error; }
        if (!data || data.length === 0) throw new Error('保存失败');
        uuid = data[0].id;
        setDraftTourId(uuid);
        navigate(`/tour/${uuid}/edit`, { replace: true });
      } else {
        await supabase.from('tours').update(tourData).eq('id', uuid);
      }

      setPhase('processing');
      setSaveMsg(`✅ 草稿已保存 (ID: ${uuid})`);
    } catch (e) {
      setSaveMsg(`❌ ${e.message}`);
    } finally {
      setSaving(false);
    }
  };

  // ── 保存基本信息（已有导览）：只更新标题/目的地等，不触发 AI 重新处理 ──
  const handleSaveBasic = async () => {
    if (!user) { setSaveMsg('请先登录'); return; }
    if (!title.trim()) { setSaveMsg('请输入标题'); return; }
    if (!draftTourId) { setSaveMsg('❌ 尚未保存草稿'); return; }
    setSaving(true);
    setSaveMsg('');
    const tourData = {
      title: title.trim(),
      subtitle: subtitle.trim(),
      theme: { primaryColor },
      source: {
        type: 'novel',
        title: novelTitle,
        author: novelAuthor,
        era: novelEra,
        synopsis: novelSynopsis,
        rawText: sourceText,
      },
      destination: { name: destName, region: destRegion, type: 'mountain' },
      is_public: isPublic,
    };
    try {
      await supabase.from('tours').update(tourData).eq('id', draftTourId);
      await reloadTour();
      setSaveMsg('✅ 基本信息已保存');
      setPhase('review');
    } catch (e) {
      setSaveMsg(`❌ ${e.message}`);
    } finally {
      setSaving(false);
    }
  };

  // ── Re-process: 重置 status=processing，触发 UPDATE 触发器重新调用 Edge Function ──
  const handleReprocess = async () => {
    if (!user) { setSaveMsg('请先登录'); return; }
    if (!draftTourId) { setSaveMsg('❌ 尚未保存草稿'); return; }
    setProcessingError('');
    try {
      await supabase.from('tours').update({ status: 'processing' }).eq('id', draftTourId);
      setRetryCount(c => c + 1); // 强制重挂载 ProcessingPhase，重置轮询
      setPhase('processing');
    } catch (e) {
      setSaveMsg(`❌ ${e.message}`);
    }
  };

  // ── Location helpers ──
  const addLocation = (loc) => {
    setLocations(prev => [...prev, loc]);
    setEditingLoc(loc);
    setShowMapSearch(false);
  };

  const removeLocation = (id) => {
    setLocations(prev => prev.filter(l => l.id !== id));
    if (editingLoc?.id === id) setEditingLoc(null);
    setRoutes(prev => prev.map(r => ({ ...r, stops: r.stops.filter(s => s !== id) })));
  };

  const updateLocation = (id, updates) => {
    setLocations(prev => prev.map(l => l.id === id ? { ...l, ...updates } : l));
    setEditingLoc(prev => prev?.id === id ? { ...prev, ...updates } : prev);
  };

  const updateLayerContent = (locId, layerKey, content) => {
    setLocations(prev => prev.map(l => {
      if (l.id !== locId) return l;
      return { ...l, layers: { ...l.layers, [layerKey]: content } };
    }));
  };

  // ── Route helpers ──
  const addRoute = () => {
    setRoutes(prev => [...prev, {
      id: `route_${Date.now()}`,
      day: `第${prev.length + 1}天`,
      title: '',
      stops: [],
      narrative: '',
    }]);
  };

  const updateRoute = (id, updates) => {
    setRoutes(prev => prev.map(r => r.id === id ? { ...r, ...updates } : r));
  };

  const removeRoute = (id) => {
    setRoutes(prev => prev.filter(r => r.id !== id));
  };

  const toggleRouteStop = (routeId, locId) => {
    setRoutes(prev => prev.map(r => {
      if (r.id !== routeId) return r;
      const exists = r.stops.includes(locId);
      return { ...r, stops: exists ? r.stops.filter(s => s !== locId) : [...r.stops, locId] };
    }));
  };

  // ── Save all (final) ──
  const handleSaveAll = async () => {
    if (!user) { setSaveMsg('请先登录'); return; }
    setSaving(true);
    setSaveMsg('');

    const tourData = {
      title: title.trim(), subtitle: subtitle.trim(),
      theme: { primaryColor },
      source: { type: 'novel', title: novelTitle, author: novelAuthor, era: novelEra, synopsis: novelSynopsis },
      destination: { name: destName, region: destRegion, type: 'mountain' },
      is_public: isPublic,
    };

    try {
      const uuid = draftTourId;
      await supabase.from('tours').update(tourData).eq('id', uuid);

      await supabase.from('content_layers').delete().eq('tour_id', uuid);
      if (contentLayers.length > 0) {
        await supabase.from('content_layers').insert(
          contentLayers.map((l, i) => ({
            tour_id: uuid, layer_key: l.id, name: l.name, icon: l.icon, color: l.color, sort_order: i,
          }))
        );
      }

      await supabase.from('locations').delete().eq('tour_id', uuid);
      if (locations.length > 0) {
        await supabase.from('locations').insert(
          locations.map((loc, i) => ({
            id: loc.id, tour_id: uuid, name: loc.name,
            lat: loc.lat, lng: loc.lng, elevation: loc.elevation || '',
            importance: loc.importance || 3, tags: loc.tags || [],
            layers: loc.layers || {}, reflection: loc.reflection || '',
            practical: loc.practical || {}, sort_order: i,
          }))
        );
      }

      await supabase.from('routes').delete().eq('tour_id', uuid);
      if (routes.length > 0) {
        await supabase.from('routes').insert(
          routes.map((r, i) => ({
            id: r.id, tour_id: uuid, day_label: r.day,
            title: r.title, stops: r.stops, narrative: r.narrative || '', sort_order: i,
          }))
        );
      }

      setSaveMsg('✅ 保存成功！');
    } catch (e) {
      setSaveMsg(`❌ ${e.message}`);
    } finally {
      setSaving(false);
    }
  };

  // ── Render ──
  if (loading) return <div className="min-h-screen bg-[#0f0f1a] flex items-center justify-center text-gray-400">加载中...</div>;
  if (!isNew && !isOwner && tour) {
    return (
      <div className="min-h-screen bg-[#0f0f1a]">
        <NavBar title="无权限" />
        <div className="flex items-center justify-center text-center p-4 pt-20">
          <div>
            <p className="text-gray-400 mb-4">你没有编辑此导览的权限</p>
            <Button onClick={() => navigate(`/tour/${tourId}`)}>返回导览</Button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0f0f1a] flex flex-col">
      {/* Header */}
      <NavBar
        title={isNew ? '创建新导览' : phase === 'input' ? '编辑基本信息' : '编辑导览'}
        rightContent={
          phase === 'review' ? (
            <Button size="sm" onClick={handleSaveAll} disabled={saving}>
              {saving ? '保存中...' : '💾 保存'}
            </Button>
          ) : false
        }
      />

      {saveMsg && (
        <div className={`px-4 py-2.5 text-xs text-center font-medium flex items-center justify-center gap-3 ${
          saveMsg.includes('✅') ? 'bg-green-600/10 text-green-400' :
          saveMsg.includes('💡') ? 'bg-blue-600/10 text-blue-400' :
          'bg-red-600/10 text-red-400'
        }`}>{saveMsg}{saveMsg.includes('✅') && <a href={`/tour/${draftTourId}`} className="underline hover:text-white transition-colors">查看导览 →</a>}</div>
      )}

      <div className="flex-1 overflow-y-auto p-4 max-w-2xl mx-auto w-full pb-24">

        {/* ════════════════════════════════════════════════ */}
        {/* PHASE 1: Input — User fills basic info + source */}
        {/* ════════════════════════════════════════════════ */}
        {phase === 'input' && (
          <div className="space-y-4">
            {/* Step indicator */}
            <div className="flex items-center gap-2 mb-2">
              <div className="w-8 h-8 rounded-full bg-red-600 text-white flex items-center justify-center text-xs font-bold">1</div>
              <div className="text-white font-semibold text-sm">基本信息与源材料</div>
              <div className="flex-1 h-px bg-white/10" />
              <div className="w-8 h-8 rounded-full bg-white/5 text-gray-500 flex items-center justify-center text-xs">2</div>
              <div className="w-8 h-8 rounded-full bg-white/5 text-gray-500 flex items-center justify-center text-xs">3</div>
            </div>

            {/* Basic info */}
            <section className="bg-[#1c1c32] rounded-2xl p-5 border border-white/5 space-y-3">
              <h2 className="text-white font-bold text-sm">📋 导览信息</h2>
              <div>
                <label className="text-gray-400 text-xs">标题 *</label>
                <input value={title} onChange={e => setTitle(e.target.value)}
                  className="w-full bg-[#0f0f1a] text-white rounded-xl px-3 py-2.5 text-sm border border-white/10 mt-1 outline-none focus:border-red-600"
                  placeholder="如：剑出衡山 · 南岳巡礼" />
              </div>
              <div>
                <label className="text-gray-400 text-xs">副标题</label>
                <input value={subtitle} onChange={e => setSubtitle(e.target.value)}
                  className="w-full bg-[#0f0f1a] text-white rounded-xl px-3 py-2.5 text-sm border border-white/10 mt-1 outline-none focus:border-red-600"
                  placeholder="如：跟着赵荣的脚步，登五神峰寻剑神之路" />
              </div>
              <div className="flex gap-3">
                <div className="flex-1">
                  <label className="text-gray-400 text-xs">目的地</label>
                  <input value={destName} onChange={e => setDestName(e.target.value)}
                    className="w-full bg-[#0f0f1a] text-white rounded-xl px-3 py-2.5 text-sm border border-white/10 mt-1 outline-none focus:border-red-600"
                    placeholder="如：南岳衡山" />
                </div>
                <div className="flex-1">
                  <label className="text-gray-400 text-xs">地区</label>
                  <input value={destRegion} onChange={e => setDestRegion(e.target.value)}
                    className="w-full bg-[#0f0f1a] text-white rounded-xl px-3 py-2.5 text-sm border border-white/10 mt-1 outline-none focus:border-red-600"
                    placeholder="如：湖南省衡阳市" />
                </div>
              </div>
              <div className="flex gap-3 items-center">
                <div>
                  <label className="text-gray-400 text-xs">主题色</label>
                  <input type="color" value={primaryColor} onChange={e => setPrimaryColor(e.target.value)}
                    className="w-10 h-10 rounded-lg border-0 cursor-pointer mt-1 bg-transparent" />
                </div>
                <label className="flex items-center gap-2 text-gray-400 text-xs">
                  <input type="checkbox" checked={isPublic} onChange={e => setIsPublic(e.target.checked)}
                    className="rounded accent-red-600" />
                  公开（其他人可见）
                </label>
              </div>
            </section>

            {/* Source materials */}
            <section className="bg-[#1c1c32] rounded-2xl p-5 border border-white/5 space-y-3">
              <h2 className="text-white font-bold text-sm">📚 源材料 — 提供得越多，AI 分析越精准</h2>
              <div>
                <label className="text-gray-400 text-xs">小说 / 作品名称</label>
                <input value={novelTitle} onChange={e => setNovelTitle(e.target.value)}
                  className="w-full bg-[#0f0f1a] text-white rounded-xl px-3 py-2.5 text-sm border border-white/10 mt-1 outline-none focus:border-red-600"
                  placeholder="如：笑傲江湖" />
              </div>
              <div className="flex gap-3">
                <div className="flex-1">
                  <label className="text-gray-400 text-xs">作者</label>
                  <input value={novelAuthor} onChange={e => setNovelAuthor(e.target.value)}
                    className="w-full bg-[#0f0f1a] text-white rounded-xl px-3 py-2.5 text-sm border border-white/10 mt-1 outline-none focus:border-red-600"
                    placeholder="如：金庸" />
                </div>
                <div className="flex-1">
                  <label className="text-gray-400 text-xs">时代背景</label>
                  <input value={novelEra} onChange={e => setNovelEra(e.target.value)}
                    className="w-full bg-[#0f0f1a] text-white rounded-xl px-3 py-2.5 text-sm border border-white/10 mt-1 outline-none focus:border-red-600"
                    placeholder="如：明代" />
                </div>
              </div>
              <div>
                <label className="text-gray-400 text-xs">故事梗概</label>
                <textarea value={novelSynopsis} onChange={e => setNovelSynopsis(e.target.value)} rows={3}
                  className="w-full bg-[#0f0f1a] text-white rounded-xl px-3 py-2.5 text-sm border border-white/10 mt-1 outline-none focus:border-red-600 resize-none"
                  placeholder="简要概述故事与目的地的关系..." />
              </div>
              <div>
                <label className="text-gray-400 text-xs">
                  小说文本 / 关键章节
                  <span className="text-gray-600 ml-1">（粘贴涉及目的地的章节文字，AI 会从中提取地点和原文引用）</span>
                </label>
                <textarea value={sourceText} onChange={e => setSourceText(e.target.value)} rows={8}
                  className="w-full bg-[#0f0f1a] text-white rounded-xl px-3 py-2.5 text-sm border border-white/10 mt-1 outline-none focus:border-red-600 resize-none font-mono"
                  placeholder={"粘贴小说中涉及该目的地的章节，AI 会从中提取地点与原文引用...\n\n留空时 AI 将基于目的地常识生成导览。"} />
              </div>

              <div className="flex gap-2">
                {draftTourId && (
                  <button
                    onClick={handleSaveBasic}
                    disabled={saving}
                    className="flex-1 py-3.5 bg-white/5 text-white rounded-xl text-sm font-bold hover:bg-white/10 transition-colors disabled:opacity-50"
                  >
                    {saving ? '⏳ 保存中...' : '💾 保存修改'}
                  </button>
                )}
                <button
                  onClick={handleSaveDraft}
                  disabled={saving}
                  className="flex-1 py-3.5 bg-gradient-to-r from-red-600 to-purple-600 text-white rounded-xl text-sm font-bold disabled:opacity-50 hover:from-red-700 hover:to-purple-700 transition-colors shadow-lg shadow-red-600/20"
                >
                  {saving ? '⏳ 保存中...' : draftTourId ? '🤖 AI 重新分析' : '🤖 AI 分析：生成地点、内容与路线'}
                </button>
              </div>
              <p className="text-gray-500 text-xs text-center leading-relaxed">
                点击「AI 分析」后全自动完成：<br/>
                ① 分析文本提取所有地点 → ② 高德 API 校验精确坐标<br/>
                ③ 生成四层内容（小说/历史/传说/民俗）→ ④ 规划游览路线 → ⑤ 写入数据库
              </p>
            </section>
          </div>
        )}

        {/* ════════════════════════════════════════════════ */}
        {/* PHASE 2: Processing — waiting for AI */}
        {/* ════════════════════════════════════════════════ */}
        {phase === 'processing' && (
          <ProcessingPhase
            key={retryCount}
            draftTourId={draftTourId}
            title={title}
            destName={destName}
            destRegion={destRegion}
            novelTitle={novelTitle}
            novelAuthor={novelAuthor}
            sourceText={sourceText}
            onCheckDone={async () => {
              // Load tour data BEFORE entering review, so user never sees blank error page
              for (let i = 0; i < 5; i++) {
                const fresh = await reloadTour();
                if (fresh && fresh.locations && fresh.locations.length > 0) {
                  setPhase('review');
                  return;
                }
                if (i < 4) await new Promise(r => setTimeout(r, (i + 1) * 2000));
              }
              setPhase('review'); // fallback: show error+retry UI
            }}
            onSkip={() => setPhase('review')}
            onBack={() => setPhase('input')}
            onRetry={handleReprocess}
          />
        )}

        {/* ════════════════════════════════════════════════ */}
        {/* PHASE 3: Review — locations, content, routes */}
        {/* ════════════════════════════════════════════════ */}
        {phase === 'review' && loading && (
          <div className="text-center py-16 text-gray-400">加载数据中...</div>
        )}
        {phase === 'review' && !loading && (!tour || (!locations.length && !routes.length)) && (
          tour ? (
            // 导览加载成功，但 AI 没有生成任何地点 —— 重试加载没用，给出正确操作
            <div className="text-center py-16 space-y-4">
              <div className="text-4xl">🗺️</div>
              <p className="text-gray-400">AI 没有生成任何地点</p>
              <p className="text-gray-500 text-xs">可能原因：源文本过少、地点未识别、或坐标校验全被过滤</p>
              <div className="flex gap-2 justify-center">
                <button onClick={() => setPhase('input')}
                  className="px-6 py-2 bg-white/5 text-muted-foreground rounded-xl text-sm">← 修改基本信息</button>
                <button onClick={handleReprocess}
                  className="px-6 py-2 bg-red-600 text-white rounded-xl text-sm">🔄 AI 重新分析</button>
              </div>
            </div>
          ) : (
            // 导览数据加载失败（网络/权限问题）
            <div className="text-center py-16 space-y-4">
              <div className="text-4xl">📡</div>
              <p className="text-gray-400">数据加载失败，请检查网络后重试</p>
              <button onClick={() => reloadTour()} className="px-6 py-2 bg-red-600 text-white rounded-xl text-sm">🔄 重试加载</button>
            </div>
          )
        )}
        {phase === 'review' && !loading && tour && (locations.length > 0 || routes.length > 0) && (
          <div className="space-y-4">
            {/* Step indicator */}
            <div className="flex items-center gap-2 mb-2">
              <div className="w-8 h-8 rounded-full bg-green-600 text-white flex items-center justify-center text-xs">✓</div>
              <div className="flex-1 h-px bg-green-600/30" />
              <div className="w-8 h-8 rounded-full bg-red-600 text-white flex items-center justify-center text-xs font-bold">2</div>
              <div className="text-white font-semibold text-sm">审核地点与内容</div>
              <div className="flex-1 h-px bg-white/10" />
              <div className="w-8 h-8 rounded-full bg-white/5 text-gray-500 flex items-center justify-center text-xs">3</div>
            </div>

            {/* 公开/私密切换 + 编辑基本信息 */}
            <div className="flex items-center gap-2 mb-3 flex-wrap">
              <button
                onClick={() => setIsPublic(!isPublic)}
                className={`flex items-center gap-2 text-xs px-3 py-2 rounded-xl border transition-colors ${
                  isPublic
                    ? 'bg-green-600/10 border-green-600/30 text-green-400'
                    : 'bg-white/5 border-white/10 text-gray-400'
                }`}
              >
                {isPublic ? '🌍 已公开（所有人可见）' : '🔒 私密（仅自己可见）'}
              </button>
              <button
                onClick={() => setPhase('input')}
                className="flex items-center gap-2 text-xs px-3 py-2 rounded-xl border border-white/10 bg-white/5 text-gray-300 hover:bg-white/10 transition-colors"
              >
                📝 编辑基本信息（标题/目的地等）
              </button>
              <span className="text-[10px] text-gray-500">点右上角「保存」后生效</span>
            </div>

            <button
              onClick={handleReprocess}
              className="w-full py-2.5 bg-purple-600/10 text-purple-400 rounded-xl text-xs border border-purple-600/20 mb-3 hover:bg-purple-600/20 transition-colors"
            >
              🔄 AI 重新分析（重新调用 AI，覆盖当前 AI 生成的地点 / 内容 / 路线）
            </button>

            {/* Locations */}
            <section className="bg-[#1c1c32] rounded-2xl p-5 border border-white/5">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-white font-bold text-sm">📍 地点 ({locations.length})</h2>
                <button onClick={() => setShowMapSearch(true)}
                  className="px-3 py-1.5 bg-red-600 text-white rounded-xl text-xs">+ 搜索添加</button>
              </div>
              {locations.length === 0 ? (
                <div className="text-center py-8">
                  <div className="text-4xl mb-3">🗺️</div>
                  <p className="text-gray-400 text-sm mb-2">还没有地点</p>
                  <p className="text-gray-500 text-xs">点击「搜索添加」打开地图搜索，或让 AI 自动生成</p>
                </div>
              ) : (
                <div className="space-y-1 max-h-60 overflow-y-auto">
                  {locations.map(loc => (
                    <button key={loc.id}
                      onClick={() => setEditingLoc(editingLoc?.id === loc.id ? null : loc)}
                      className={`w-full text-left px-3 py-2 rounded-xl transition-colors ${
                        editingLoc?.id === loc.id ? 'bg-red-600/10 border border-red-600/20' : 'bg-[#0f0f1a] hover:bg-[#242444]'
                      }`}>
                      <div className="flex items-center justify-between">
                        <span className="text-white text-xs">{'⭐'.repeat(loc.importance || 1)} {loc.name}</span>
                        <span className="text-gray-500 text-xs">{loc.lng?.toFixed(4)}, {loc.lat?.toFixed(4)}</span>
                      </div>
                    </button>
                  ))}
                </div>
              )}
            </section>

            {/* Location editor */}
            {editingLoc && (
              <section className="bg-[#1c1c32] rounded-2xl p-5 border border-white/5 space-y-3">
                <div className="flex items-center justify-between">
                  <h3 className="text-white font-bold text-sm">✏️ {editingLoc.name}</h3>
                  <button onClick={() => removeLocation(editingLoc.id)}
                    className="px-3 py-1 bg-red-600/10 text-red-400 rounded-xl text-xs">删除</button>
                </div>
                <div className="flex gap-2">
                  <input value={editingLoc.name}
                    onChange={e => updateLocation(editingLoc.id, { name: e.target.value })}
                    className="flex-1 bg-[#0f0f1a] text-white rounded-lg px-3 py-2 text-xs border border-white/10 outline-none" />
                  <select value={editingLoc.importance}
                    onChange={e => updateLocation(editingLoc.id, { importance: parseInt(e.target.value) })}
                    className="bg-[#0f0f1a] text-white rounded-lg px-2 py-2 text-xs border border-white/10 outline-none">
                    {[1,2,3,4,5].map(n => <option key={n} value={n}>{'⭐'.repeat(n)}</option>)}
                  </select>
                  <input value={editingLoc.elevation || ''}
                    onChange={e => updateLocation(editingLoc.id, { elevation: e.target.value })}
                    className="w-24 bg-[#0f0f1a] text-white rounded-lg px-3 py-2 text-xs border border-white/10 outline-none" placeholder="海拔" />
                </div>
                <input value={(editingLoc.tags || []).join(', ')}
                  onChange={e => updateLocation(editingLoc.id, { tags: e.target.value.split(',').map(t => t.trim()).filter(Boolean) })}
                  className="w-full bg-[#0f0f1a] text-white rounded-lg px-3 py-2 text-xs border border-white/10 outline-none"
                  placeholder="标签（逗号分隔）" />
                <div>
                  <div className="flex gap-1 mb-2 flex-wrap">
                    {contentLayers.map(layer => (
                      <button key={layer.id} onClick={() => setEditingLayer(layer.id)}
                        className="px-2 py-1 rounded-full text-xs"
                        style={{
                          background: editingLayer === layer.id ? layer.color : 'transparent',
                          color: editingLayer === layer.id ? '#fff' : '#888',
                          border: editingLayer === layer.id ? 'none' : '1px solid rgba(255,255,255,0.1)',
                        }}>{layer.icon} {layer.name}</button>
                    ))}
                  </div>
                  <textarea
                    value={typeof (editingLoc.layers || {})[editingLayer] === 'string'
                      ? (editingLoc.layers || {})[editingLayer]
                      : ((editingLoc.layers || {})[editingLayer]?.text || '')}
                    onChange={e => updateLayerContent(editingLoc.id, editingLayer, e.target.value)} rows={4}
                    className="w-full bg-[#0f0f1a] text-white rounded-lg px-3 py-2 text-xs border border-white/10 outline-none resize-none"
                    placeholder="此分类内容（AI 可自动填充）" />
                </div>
                <textarea value={editingLoc.reflection || ''}
                  onChange={e => updateLocation(editingLoc.id, { reflection: e.target.value })} rows={2}
                  className="w-full bg-[#0f0f1a] text-white rounded-lg px-3 py-2 text-xs border border-white/10 outline-none resize-none"
                  placeholder="💭 停下来想一想" />
                <div className="flex gap-2">
                  <input value={(editingLoc.practical || {}).access || ''}
                    onChange={e => updateLocation(editingLoc.id, { practical: { ...editingLoc.practical, access: e.target.value } })}
                    className="flex-1 bg-[#0f0f1a] text-white rounded-lg px-3 py-2 text-xs border border-white/10 outline-none" placeholder="到达方式" />
                  <input value={(editingLoc.practical || {}).difficulty || ''}
                    onChange={e => updateLocation(editingLoc.id, { practical: { ...editingLoc.practical, difficulty: e.target.value } })}
                    className="flex-1 bg-[#0f0f1a] text-white rounded-lg px-3 py-2 text-xs border border-white/10 outline-none" placeholder="难度" />
                </div>
              </section>
            )}

            {/* Routes section */}
            <section className="bg-[#1c1c32] rounded-2xl p-5 border border-white/5">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-white font-bold text-sm">🗺 游览路线 ({routes.length})</h2>
                <button onClick={addRoute} className="px-3 py-1.5 bg-red-600 text-white rounded-xl text-xs">+ 添加路线</button>
              </div>
              {routes.length === 0 ? (
                <div className="text-center py-6">
                  <div className="text-4xl mb-3">🥾</div>
                  <p className="text-gray-400 text-sm mb-1">还没有路线</p>
                  <p className="text-gray-500 text-xs">AI 可根据地点自动规划真实徒步路线，你也可以手动创建</p>
                </div>
              ) : (
                routes.map(route => (
                  <div key={route.id} className="bg-[#0f0f1a] rounded-xl p-3 mb-2 border border-white/5">
                    <div className="flex gap-2 items-center mb-2">
                      <input value={route.day}
                        onChange={e => updateRoute(route.id, { day: e.target.value })}
                        className="w-20 bg-[#1c1c32] text-white rounded-lg px-2 py-1.5 text-xs outline-none" placeholder="第1天" />
                      <input value={route.title}
                        onChange={e => updateRoute(route.id, { title: e.target.value })}
                        className="flex-1 bg-[#1c1c32] text-white rounded-lg px-2 py-1.5 text-xs outline-none" placeholder="路线标题" />
                      <button onClick={() => removeRoute(route.id)}
                        className="text-red-400 text-xs px-2 py-0.5 rounded-full bg-red-600/10">删除</button>
                    </div>
                    <textarea value={route.narrative}
                      onChange={e => updateRoute(route.id, { narrative: e.target.value })} rows={2}
                      className="w-full bg-[#1c1c32] text-white rounded-lg px-2 py-1.5 text-xs outline-none resize-none mb-2"
                      placeholder="路线叙事" />
                    <div className="flex flex-wrap gap-1">
                      {locations.map(loc => {
                        const inRoute = route.stops.includes(loc.id);
                        return (
                          <button key={loc.id} onClick={() => toggleRouteStop(route.id, loc.id)}
                            className={`px-2 py-1 rounded-full text-xs transition-colors ${
                              inRoute ? 'bg-red-600 text-white' : 'bg-[#1c1c32] text-gray-500'
                            }`}>{inRoute && '✓ '}{loc.name}</button>
                        );
                      })}
                    </div>
                    {route.stops.length > 0 && (
                      <div className="text-gray-500 text-xs mt-2">
                        途经: {route.stops.map(id => locations.find(l => l.id === id)?.name || id).join(' → ')}
                      </div>
                    )}
                  </div>
                ))
              )}
            </section>
          </div>
        )}
      </div>

      <MapSearchModal
        show={showMapSearch}
        onClose={() => setShowMapSearch(false)}
        onAdd={addLocation}
        initialRegion={destRegion}
      />
    </div>
  );
}
